# Site settings
# in the templates available like {{ site.myvariable }}.
title: Blog của Yuki Mắt Hý
email: yukimathy@domain.com
brand: Yuki Mắt Hý
headline: Thích đi và suy tư
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: kieuhy.mk92@gmail.com
phone: 0917 000 000

# Tracking
googleAnalitycsID: UA-83933844-1

